name: Tests
run-name: Test `exports-to-sheet` API
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Hurl
        uses: gacts/install-hurl@v1

      - name: Generate DB password
        id: password
        uses: aammirmirza/RandomPasswordGenerator@v1.1
        with:
          length: 18

      - name: Install SQL Server
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlclient, sqlpackage
          sa-password: ${{ steps.password.outputs.password }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache Node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Import test data
        run: |
          sqlcmd -S localhost -U sa -P "${{ steps.password.outputs.password }}"" -i ./tests/test.sql

      - name: Build app
        run: npm run build

      - name: Start app
        run: npm run start &
        env:
          DB_HOST: localhost
          DB_PASS: ${{ steps.password.outputs.password }}
          DB_USER: sa
          TRANSACTION_KEY: _QLn9wAxP_U89aBBOqz0VSBD6L3czl-7FMFo1QipwU3O8JDpuBHVTrh8oeOXDwXq

      - name: Run tests
        run: |
          hurl --variable token=X1FMbjl3QXhQX1U4OWFCQk9xejBWU0JENkwzY3psLTdGTUZvMVFpcHdVM084SkRwdUJIVlRyaDhvZU9YRHdYcQ== --test tests/*.hurl
